// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe8wsBDwZsamsvQrmMZZBnR2J2rP-XZuo',
    appId: '1:895584338653:web:9964e0edf550a2c78f5134',
    messagingSenderId: '895584338653',
    projectId: 'naval1gifty',
    authDomain: 'naval1gifty.firebaseapp.com',
    storageBucket: 'naval1gifty.firebasestorage.app',
    measurementId: 'G-49Q3W52RZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvmVoqBXiHG9HwjO10R-mJNc9xbZvsmLM',
    appId: '1:895584338653:android:fa986daa0f954a288f5134',
    messagingSenderId: '895584338653',
    projectId: 'naval1gifty',
    storageBucket: 'naval1gifty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSxY-XYhADGnECcf0z1zQmKrkNNLAuSIQ',
    appId: '1:895584338653:ios:b3ec386b95bb9eeb8f5134',
    messagingSenderId: '895584338653',
    projectId: 'naval1gifty',
    storageBucket: 'naval1gifty.firebasestorage.app',
    iosBundleId: 'com.example.naval1gifty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSxY-XYhADGnECcf0z1zQmKrkNNLAuSIQ',
    appId: '1:895584338653:ios:b3ec386b95bb9eeb8f5134',
    messagingSenderId: '895584338653',
    projectId: 'naval1gifty',
    storageBucket: 'naval1gifty.firebasestorage.app',
    iosBundleId: 'com.example.naval1gifty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe8wsBDwZsamsvQrmMZZBnR2J2rP-XZuo',
    appId: '1:895584338653:web:5dbe1fbd22b476eb8f5134',
    messagingSenderId: '895584338653',
    projectId: 'naval1gifty',
    authDomain: 'naval1gifty.firebaseapp.com',
    storageBucket: 'naval1gifty.firebasestorage.app',
    measurementId: 'G-YH2VVV1ME6',
  );
}
